# Generated by Django 4.2.2 on 2023-06-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, unique=True)),
                ('Mobile', models.BigIntegerField(unique=True)),
                ('Home', models.BigIntegerField(blank=True, null=True)),
                ('Desc', models.TextField(blank=True, null=True)),
                ('ClinicNum', models.BigIntegerField(blank=True, null=True)),
                ('ClinicAdd', models.TextField(blank=True, null=True)),
                ('IdDoctor', models.BigIntegerField(unique=True)),
                ('ClinicShift', models.TextField(blank=True, null=True)),
                ('Prof', models.CharField(choices=[('ارتوپدی', 'ارتوپدی'), ('اورولوژی', 'اورولوژی'), ('اطفال', 'اطفال'), ('پزشک عمومی', 'پزشک عمومی'), ('جراح عمومی', 'جراح عمومی'), ('جراحی مغز و اعصاب', 'جراحی مغز و اعصاب'), ('داخلی', 'داخلی'), ('نورولوژی', 'نورولوژی'), ('زنان و زایمان', 'زنان و زایمان'), ('قلب و عروق', 'قلب و عروق'), ('گوش و حلق و بینی', 'گوش و حلق و بینی')], max_length=300)),
                ('Prof2', models.CharField(choices=[('پزشک عمومی', 'پزشک عمومی'), ('جراحی استخوان', 'جراحی استخوان'), ('اکوکاردیوگرافی', 'اکوکاردیوگرافی'), ('اینترونشنال کاردیوگرافی', 'اینترونشنال کاردیوگرافی'), ('برست', 'برست'), ('جراحی درون بین', 'جراحی درون بین'), ('جراحی درون بین لاپارسکوپی', 'جراحی درون بین لاپارسکوپی'), ('جراحی سرطان', 'جراحی سرطان'), ('رینولوژی', 'رینولوژی')], max_length=300)),
                ('IMG', models.ImageField(upload_to='media')),
                ('Hospital', models.CharField(choices=[('نیکان غرب', 'نیکان غرب'), ('نیکان اقدسیه', 'نیکان اقدسیه'), ('نیکان شرق', 'نیکان شرق')], max_length=300)),
                ('HospitalExtra', models.CharField(blank=True, max_length=300)),
                ('Username', models.CharField(blank=True, max_length=300, null=True)),
                ('Password', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, unique=True)),
                ('Mobile', models.BigIntegerField(unique=True)),
                ('IdPerson', models.BigIntegerField(unique=True)),
                ('Home', models.BigIntegerField(blank=True, null=True)),
                ('About', models.TextField(blank=True, null=True)),
                ('Hospital', models.CharField(choices=[('نیکان غرب', 'نیکان غرب'), ('نیکان اقدسیه', 'نیکان اقدسیه'), ('نیکان شرق', 'نیکان شرق')], max_length=300)),
                ('Username', models.CharField(blank=True, max_length=300, null=True)),
                ('Password', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, unique=True)),
                ('Mobile', models.BigIntegerField(unique=True)),
                ('IdPersonnel', models.BigIntegerField(unique=True)),
                ('Home', models.BigIntegerField(blank=True, null=True)),
                ('Section', models.CharField(choices=[('سپند', 'سپند'), ('سپهر', 'سپهر'), ('ستایش', 'ستایش'), ('سپید', 'سپید')], max_length=300)),
                ('Post', models.CharField(choices=[('پرستار', 'پرستار'), ('کاخدار', 'کاخدار'), ('منشی', 'منشی'), ('کمک بهیار', 'کمک بهیار'), ('کارشناس', 'کارشناس')], max_length=300)),
                ('Hospital', models.CharField(choices=[('نیکان غرب', 'نیکان غرب'), ('نیکان اقدسیه', 'نیکان اقدسیه'), ('نیکان شرق', 'نیکان شرق')], max_length=300)),
                ('Username', models.CharField(blank=True, max_length=300, null=True)),
                ('Password', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
