# Generated by Django 4.2.2 on 2023-06-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='IdDoctor',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='IdPerson',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IdPersonnel',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='Name',
            field=models.CharField(max_length=300),
        ),
    ]
