# Generated by Django 4.2.2 on 2023-06-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_doctor_iddoctor_alter_doctor_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='HospitalExtra',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='HospitalExtra',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='IMG',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
