# Generated by Django 4.2.2 on 2023-06-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_doctor_is_active_person_hospitalextra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='IdDoctor',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='IdPerson',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IdPersonnel',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='Name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
