# Generated by Django 4.2.2 on 2023-06-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_doctor_table_alter_person_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table='Doctor_view_table',
        ),
        migrations.AlterModelTable(
            name='person',
            table='Person_view_table',
        ),
        migrations.AlterModelTable(
            name='personnel',
            table='Personnel_view_table',
        ),
    ]
