# Generated by Django 4.2.2 on 2023-06-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_doctor_table_alter_person_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table='view_table',
        ),
    ]
