# Generated by Django 4.2.2 on 2023-06-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_doctor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
        migrations.AlterModelTable(
            name='personnel',
            table=None,
        ),
    ]
