# Generated by Django 4.2.2 on 2023-06-26 04:49

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_doctor_table_alter_person_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='IMG',
            field=models.ImageField(blank=True, null=True, upload_to=polls.models.PathAndRename.wrapper),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='Name',
            field=models.CharField(max_length=300),
        ),
    ]
