# Generated by Django 4.2.2 on 2023-06-26 04:55

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_doctor_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='IDIMG',
            field=models.CharField(default='P', max_length=300),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='IMG',
            field=models.ImageField(blank=True, null=True, upload_to=polls.models.PathAndRename.wrapper),
        ),
    ]
