# Generated by Django 4.2.2 on 2023-06-26 05:04

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_person_idimg_person_img_personnel_idimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='IMG',
            field=models.ImageField(blank=True, null=True, upload_to=polls.models.PathAndRename.wrapper),
        ),
        migrations.AlterField(
            model_name='person',
            name='IMG',
            field=models.ImageField(blank=True, null=True, upload_to=polls.models.PathAndRename.wrapper),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IMG',
            field=models.ImageField(blank=True, null=True, upload_to=polls.models.PathAndRename.wrapper),
        ),
    ]
