# Generated by Django 4.2.2 on 2023-06-26 05:11

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_doctor_img_alter_person_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='IDIMG',
        ),
        migrations.RemoveField(
            model_name='person',
            name='IDIMG',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='IDIMG',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='IMG',
            field=models.ImageField(blank=True, null=True, upload_to=polls.models.PathAndRename.wrapper),
        ),
        migrations.AlterField(
            model_name='person',
            name='IMG',
            field=models.ImageField(blank=True, null=True, upload_to=polls.models.PathAndRename.wrapper),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IMG',
            field=models.ImageField(blank=True, null=True, upload_to=polls.models.PathAndRename.wrapper),
        ),
    ]
